server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:5174; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        resolver 8.8.8.8 valid=30s;
        
      
        set $google_script "https://script.google.com/macros/s/AKfycbzwvSrKaCPw1kvD0ENwUpuGzLZRULOvJAxHVK7uoDN3UMQtavFasHfuaUgiU0FZebnj-w/exec";
        
        proxy_pass $google_script;

     
        proxy_ssl_server_name on;
        proxy_set_header Host script.google.com;
        
       
        proxy_intercept_errors on;
        error_page 301 302 307 = @handle_redirect;
    }


    location @handle_redirect {
        set $saved_redirect_location $upstream_http_location;
        proxy_pass $saved_redirect_location;
    }
}