apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      # Tambahkan bagian ini untuk otentikasi GHCR
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: react
          image: ghcr.io/smforg11/qr-form:20260904-094845
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
