name: Auto Deploy (git pull on server)

on:
  push:
    branches:
      - main    

jobs:
  deploy:
    runs-on: self-hosted   
    steps:
      - name: Pull latest code
        run: |
          cd /opt/production-app 
          git reset --hard
          git pull origin main
          docker compose down
          docker compose up -d

          echo "✅ Git pull sukses di $(hostname)"
